name: ✨ Feature Request
description: Suggest a feature request
title: "feat:"
labels: ["enhancement"]
body:
  - type: textarea
    id: what-feature
    attributes:
      label: What feature?
      placeholder: Add descriptions
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Add screenshots
      placeholder: Add screenshots
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: "Record"
      options:
        - label: I have checked the existing [issues](https://github.com/FrancescoXX/contentbox/issues)
          required: true

        - label: I want to work on this issue
